# Generated by Django 3.2.15 on 2022-09-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=100, verbose_name='Наименование')),
                ('places', models.TextField(verbose_name='Адрес магазина')),
                ('description', models.CharField(max_length=100, verbose_name='Ближайшее метро')),
            ],
        ),
    ]
