# Generated by Django 3.2.15 on 2022-09-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='test',
            field=models.CharField(default=None, max_length=100, verbose_name='Ntcn'),
        ),
    ]
