# Generated by Django 3.2.15 on 2022-09-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Цветочный магазин', 'verbose_name_plural': 'Цветочные магазины'},
        ),
    ]
